### ISSUE TITLE
V10.0.0-release crash

### ISSUE THREAD

**Issue by Rithenar** [Mari023/AE2WirelessTerminalLibrary#119]
I got this crash in my world. I do not have a wireless terminal nor I have started with any AE2 progression yet. 

MC: 1.18
Modloader: Fabric
Version: V10.0.0-release
Modpack : Benchmark II

https://gist.github.com/Rithenar/858d28a61544f2229d68db5059df3334

**Comment by Mari023** [comment]
I am not able to reproduce this, but I think I know why It might happen
can you try if it also crashes with [this](https://github.com/Mari023/AE2WirelessTerminalLibrary/actions/runs/1733907352) build?

**Comment by Rithenar** [comment]
I will be glad to. It hasn't happened again though so maybe it was a hiccup. I will update the ticket if it does. Thank you
