### ISSUE TITLE
Charge too slowly

### ISSUE THREAD

**Issue by SkeletonCold** [Mari023/AE2WirelessTerminalLibrary#12]
Put any Terminal into Charger.Them charge slowly....
(I paint the texture for WCT,I'm not good at painting.....)
![2021-04-01_14 57 47](https://user-images.githubusercontent.com/72563159/113255665-abfe9680-92fa-11eb-9921-bf0a0827d239.png)
ummm.....another problem here.(so i need to open 2 issues?)
When you put Infinity Booster Card into terminal.Them will cost more energy(may this is your setting)
When you put out the card.Terminal still cost more energy.
And player stay in the range of Wireless Access Point, the "terminal with Infinity Booster Card" still cost more energy.
Sorry,my english is not very good....

**Comment by SkeletonCold** [comment]
The second problem may you put in the card,they will add a NBT on terminal.
when you put out the card,they can't take the NBT away form terminal.

**Comment by Mari023** [comment]
> The second problem may you put in the card,they will add a NBT on terminal.
> when you put out the card,they can't take the NBT away form terminal.

this is because it stores the actual itemStack.
when you take out the item, it will store the empty ItemStack

**Comment by Mari023** [comment]
> ummm.....another problem here.(so i need to open 2 issues?)
> When you put Infinity Booster Card into terminal.Them will cost more energy(may this is your setting)
> When you put out the card.Terminal still cost more energy.
> And player stay in the range of Wireless Access Point, the "terminal with Infinity Booster Card" still cost more energy.
I very recently did some changes to the power usage (it was way of from where it should be)

It should now work like this:
when in range of a wireless access point: draw the same amount of power as the wireless terminal
when out of range: draw twice the amount of power as the wireless Terminal at maximum range (512 blocks)

there is still a bug with how it draws this power, but it should on average work like this

**Comment by SkeletonCold** [comment]
@Mari023 Thanks your work,sir.
And though my test,
THOSE NUMBER IS NOT 100% RIGHT.

no the card:
In the range of Wireless Access Point:32AE
Out of the range:5AE
512 blocks away fo the range:5AE

put in card:
In the range of Wireless Access Point:24AE
Out of the range:11616AE
512 blocks away fo the range:11616AE

put out the card:
In the range of Wireless Access Point:39AE
Out of the range:5AE
512 blocks away fo the range:5AE

ummm....those may help you.
At the last,I ONLY test on the latest version.not do test on the version before you change some things about power.
(how about the texture pack of WCT,i want get a feedback...)

**Comment by Mari023** [comment]
So I did some testing myself, and for me it worked like expected:
if in range of an access point it draws exactly the same amount of power like the wireless terminal from ae2
if out of range it draws twice the amount of power it would draw if it were at 512 blocks away
