### ISSUE TITLE
[Feature Request] Magnet Card item blacklist

### ISSUE THREAD

**Issue by RubyRezal** [Mari023/AE2WirelessTerminalLibrary#124]
The magnet card is a great feature, but using it in ME mode while also using thrown weapons like Tridents (vanilla and Impaled) and Bontania's Chakram... it gets frustrating to have to constantly switch magnet modes and/or fish thrown weapons back out of ME storage.

A configurable blacklist would be very much appreciated.

**Comment by Mari023** [comment]
A white/blacklist is a planned feature since the beginning, but I never had the time to implement it.

**Comment by Mari023** [comment]
implemented in #132, will be in the next release
