### ISSUE TITLE
Config Screen issue

### ISSUE THREAD

**Issue by StarskyXIII** [Mari023/AE2WirelessTerminalLibrary#127]
AE2WTLib 10.1.1-beta.4
Applied Energistics 2 10.1.0-beta.2
Cloth Config API 6.2.57
Fabric API 0.46.4
![image](https://user-images.githubusercontent.com/71606873/153750378-8f6f4cf9-5a73-4f11-80f4-76cc81120fa1.png)

**Comment by Mari023** [comment]
looks like that got messed up when porting to architectury aswell.
I didn't even now / is a leagal character in a translation key.
will be fixed in the next release.
