### ISSUE TITLE
 10.1.1-beta.6-forge crash. Forgot to register something?

### ISSUE THREAD

**Issue by border999** [Mari023/AE2WirelessTerminalLibrary#133]
[crash-2022-04-16_11.42.18-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/8500317/crash-2022-04-16_11.42.18-client.txt)

**Comment by Mari023** [comment]
update your ae2wtlib version
you need an 11.x.x version of ae2wtlib (e.g. 11.0.0-alpha.2) for ae2 11.0.0-alpha.4
