### ISSUE TITLE
universal terminal energy drains super fast when in other dimension

### ISSUE THREAD

**Issue by Cop4Terminator** [Mari023/AE2WirelessTerminalLibrary#137]
just what the title says. i tried tweaking the configs but it dosen't seem to do anything.

**Comment by Mari023** [comment]
it drains the same amount of energy when it is in the same dimension, but outside the range of an access point.
yes it is quite a lot of energy, but it can't be much less than that or it will consume LESS energy than at the edge of reception of an access point with a stack of booster cards
