### ISSUE TITLE
Crash in Single player when placed in ring curio slot

### ISSUE THREAD

**Issue by sadovsf** [Mari023/AE2WirelessTerminalLibrary#141]
Hello, originally i reported this to author of original AE2 here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6352

Did not realize its separate mod. All details should be there, let me know if you need something more. Note only save revert helped at the end

**Comment by Mari023** [comment]
fixed by 6ac0b1ef0f591cd9218c54f681b928b24f35a595

**Comment by sadovsf** [comment]
Yesterday tested and seems to be working for sure. Thank you! :)
