### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by castilio20** [Mari023/AE2WirelessTerminalLibrary#142]
[crash-2022-06-14_15.13.15-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/8899639/crash-2022-06-14_15.13.15-client.txt)
version AE2WTLib-11.1.0

**Comment by Mari023** [comment]
how did you get that crash?
I looked at the code, and this should be impossible to happen

**Comment by castilio20** [comment]
i just crafter somthing from IF and bam crash wierd bc i didnt touch anything from this mod yet or open  curios

**Comment by Mari023** [comment]
b8ad7caec85d93c238fb4fb9c04a0b0fbbf024d1 should hopefully fix this, although I couldn't test this
