### ISSUE TITLE
A matter of life and coding

### ISSUE THREAD

**Issue by Domaman202** [Mari023/AE2WirelessTerminalLibrary#150]
In order for the magnetic card to work we call "doMagnet" EVERY SERVER TICK?
I understand correctly?

**Comment by Domaman202** [comment]
Why not call "doMagnet" every tick of the player's inventory?

**Comment by Domaman202** [comment]
Just this way I'm going to implement "Charger Card"

**Comment by Mari023** [comment]
> In order for the magnetic card to work we call "doMagnet" EVERY SERVER TICK? I understand correctly?

Yes, we do.
I have seen spark reports, it doesn't cause that big of a load, but if item ticks do what we need, that would really simplify the code.

**Comment by Mari023** [comment]
Item#inventoryTick does exactly what we need, but it doesn't work in Trinket Slots (tho we could fix that)

**Comment by Domaman202** [comment]
Haha! Error trace -> #150
![image](https://user-images.githubusercontent.com/51743763/187244802-40d4c680-2c2a-45ff-9072-547c46a5f208.png)
