### ISSUE TITLE
Infinity Booster Card works only in the first two upgrade slots

### ISSUE THREAD

**Issue by uselessSABOTAGE** [Mari023/AE2WirelessTerminalLibrary#154]
As mentioned on CurseForge, the inifinity booster card does not provide extended range, even beyond a few blocks of the default AE2 ME Wireless Access Point.

I have included the requested screenshot and the forced crash logs below.  Please let me know if you need anything else. 

![2022-08-30_19 14 54](https://user-images.githubusercontent.com/100305564/187565565-dcd44c6d-b996-481d-88da-707d5367715c.png)
[crash-2022-08-30_19.17.59-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/9457314/crash-2022-08-30_19.17.59-client.txt)

**Comment by Mari023** [comment]
I cannot reproduce it, what is the error message you get when trying to open the terminal?
If it is "Station cannot be located", then the issue is that your network is not loaded

**Comment by uselessSABOTAGE** [comment]
Please see the screenshot below.  I pointed at my wireless access point with my cursor so you can see I am not far. 

![2022-08-31_07 01 03](https://user-images.githubusercontent.com/100305564/187673860-b9800a08-c798-49c3-adec-aef0c00ac350.png)

**Comment by Mari023** [comment]
That is weird.
your setup should totally work.
I can't reproduce it tho, it works for me.

**Comment by Mari023** [comment]
OH
I can totally reproduce it now
It works if the infinity booster card is in the first two upgrade slots
It doesn't work when the card is in any other slots

**Comment by uselessSABOTAGE** [comment]
So, move my card to the top spot and I am good to go?

**Comment by Mari023** [comment]
yes

**Comment by Mari023** [comment]
I'll still have to fix this bug tho

**Comment by uselessSABOTAGE** [comment]
Ok, thank you!  I'm glad you were able to sort it.
