### ISSUE TITLE
new texture pack

### ISSUE THREAD

**Issue by SkeletonCold** [Mari023/AE2WirelessTerminalLibrary#16]
[ae2wtlib.zip](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/6244097/ae2wtlib.zip)

**Comment by Mari023** [comment]
I uploaded the Chinese translations.
I am not 100% sure on the textures yet, I will probably decide about that in the next few days.

**Comment by Mari023** [comment]
I'll close this since I will hopefully get Textures from the same person who also made the new Applied Energistics 2 textures

**Comment by SkeletonCold** [comment]
ok,i know
