### ISSUE TITLE
Reconnect not possible... 

### ISSUE THREAD

**Issue by SnowBerryZ** [Mari023/AE2WirelessTerminalLibrary#178]
Hello Guys,

I have an weird Issue after used "Infinity Booster Card" i can't connecting the Wireless with or without ...
He say every I'm not near the ME-System ... (2 blocks left from...)

It's possible to erase, delete the Entry in Level.dat for an reset?

But other Players have no Problems, when the Card no touched ...

Sorry i'm German...

Greetz Snow

**Comment by Mari023** [comment]
for future reference: in the ae2 config, all values relate to the wireless terminal were set to 0.05, making the range of the access point basically 0m
