### ISSUE TITLE
R removes all armor 

### ISSUE THREAD

**Issue by thezombieslaya65** [Mari023/AE2WirelessTerminalLibrary#180]
when searching for an item searighing something like uranium will cause all armor to be removed from the player and put into the crafting grid witch is a major cause for annoyance tried messing with the settings and was unbale to disable this "feture" but no such setting was pressant found out that the key R is the button that removes all armor but nothing was bound to it please add a way to disable this if it was intended

**Comment by Mari023** [comment]
Presumably this happens because you have a missbehaving  inventory sorting mod.

If you tell me which one it is, I can maybe look if I can do something to blacklist it in the Terminal, but most sorting mods don't have that.
