### ISSUE TITLE
Crash Upon Launch

### ISSUE THREAD

**Issue by BobminiJr** [Mari023/AE2WirelessTerminalLibrary#181]
I was able to figure out that Applied Energistics 2 Wireless Terminals was crashing my game every time I launch it, I don't even get to the missing files screen in Minecraft, it just brings be back to the Minecraft launcher and gives me exit code 1. I don't know what to do, I looked it up on the internet and all I could find was people crashing mid game, no crashes upon launch. I need help.

**Comment by Mari023** [comment]
this is probably a duplicate of #163
