### ISSUE TITLE
[1.19.2] - Crash During Startup

### ISSUE THREAD

**Issue by ToxinZangoose** [Mari023/AE2WirelessTerminalLibrary#184]
Hello,

I recently tried out this mod on my personal modpack and found that it crashed when applying mixins and it appears to be something with the restocking.

If there's any mod that is known to cause issues with this, let me know, I'd love to use these wireless terminals.

Here is the log file for the instance I'm running.
[latest.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/10452266/latest.log)

**Comment by Mari023** [comment]
duplicate of #163
sadly I have not been able to find a reason why it crashes, it seems to be some mod conflict, but it is very inconsistent.
