### ISSUE TITLE
Quantum bridge card compatibility with compact machines

### ISSUE THREAD

**Issue by BanzaiRun** [Mari023/AE2WirelessTerminalLibrary#186]
Although the card works across dimensions (including custom dimensions) it doesn't inside a compact machine.

**Comment by Mari023** [comment]
Is the network loaded?
there shouldn't be anything special about the compact machines dimension

**Comment by BanzaiRun** [comment]
Chunk? yes..... 
The inventory shows briefly then disappears

**Comment by BanzaiRun** [comment]
https://user-images.githubusercontent.com/8942699/214384954-65aa26db-7c05-4655-ac7d-bda528d677a2.mp4

**Comment by Mari023** [comment]
I have seen this issue before, but I don't quite know what causes it.

there are two options I can think of:
1. Your network doesn't have enough power / it uses more power in a tick than it can store (one dense cell would be enough)
2. the chunkloading doesn't work

**Comment by BanzaiRun** [comment]
Spot on, one dense cell and issue resolved, thanks.

(Weird that it's ok in other dimensions though /shrug)
