### ISSUE TITLE
Dependency error on Quilt/Fabric

### ISSUE THREAD

**Issue by Sunconure11** [Mari023/AE2WirelessTerminalLibrary#191]
![fabric 1](https://user-images.githubusercontent.com/5614902/224057555-ebc49eba-2dfc-46a0-8241-69394989234c.png)

**Comment by Sunconure11** [comment]
This happens on 1.19.2.

**Comment by Mari023** [comment]
you are using a 1.19.3 version of ae2wtlib, you have to use a 12.x.x version for minecraft 1.19.2 / ae2 12.x.x
