### ISSUE TITLE
[1.18.2 Fabric Crash] Trying to open magnet filter button crashes game

### ISSUE THREAD

**Issue by TheUnderTaker11** [Mari023/AE2WirelessTerminalLibrary#195]
[crash-2023-04-10_15.09.12-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/11193640/crash-2023-04-10_15.09.12-client.txt)

Mod version = AE2WTLib-11.6.3

Trying to open it from wireless terminal that has magnet card upgrade installed causes game to crash with posted crash report.

**Comment by Mari023** [comment]
1.18.2 is not supported anymore
