### ISSUE TITLE
game don't lunch (crash) in 1.19.2 forge

### ISSUE THREAD

**Issue by JellyRoad** [Mari023/AE2WirelessTerminalLibrary#196]
crash game with mod like starlite, Storage Drawers, Radon on forge

**Comment by JellyRoad** [comment]
[latest.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/11242502/latest.log)

**Comment by Mari023** [comment]
great.
#163 strikes again...
something is wrong with probably all my mixins on 1.19.2, and I don't know what

**Comment by JellyRoad** [comment]
yea in log it say somethink is not right with mixing with ae2

**Comment by Mari023** [comment]
I am closing in favor of the other issue (it is the same underlying problem)
