### ISSUE TITLE
Wireless Autocraftstatus GUI wont open. 

### ISSUE THREAD

**Issue by Nexow91** [Mari023/AE2WirelessTerminalLibrary#202]
Hello what is known that the manufacturing menu does not open via the wireless tablet ? The wireless tablet also works so far, I can also autocrafting operate so trigger but if I want to see how far the status is I can not do this via the wireless terminal. I click on it but it does not open, via the normal terminal this works. 

Here is a list of mods that I use an my minecraft version is "1.16.5". 
I hope any can help me. 

bettermobgriefinggamerule-1.16.5-9.0.1.jar
betterspawnercontrol_1.16.5-3.0.jar
BetterStrongholds-1.16.4-1.2.1.jar
Bookshelf-Forge-1.16.5-10.4.33.jar
bottleyourxp_1.16.5-1.6.jar
breedablekillerrabbit_1.16.5-1.6.jar
caelus-forge-1.16.5-2.1.3.2.jar
catalogue-1.6.1-1.16.5.jar
champions-forge-1.16.5-2.0.1.16.jar
charm-forge-1.16.4-2.1.9.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
chunkloaders-1.2.3-forge-mc1.16.jar
ClientTweaks_1.16.3-5.3.0.jar
cloth-config-4.16.91-forge.jar
Clumps-6.0.0.28.jar
CodeChickenLib-1.16.5-4.0.7.445-universal.jar
collective-1.16.5-5.49.jar
configured-1.5.4-1.16.5.jar
constructionwand-1.16.5-2.6.jar
Controlling-7.0.0.29.jar
cookiecore-1.16.5-3.3.1-9c789ef.jar
corpsecomplex-forge-1.16.5-4.0.2.8.jar
CosmeticArmorReworked-1.16.5-v5.jar
cosmoslibrary-1.16.5-6.8.0-universal.jar
craftingstation-4.2.jar
CraftTweaker-1.16.5-7.1.2.520.jar
createaddition-1.16.5-20220129a.jar
createdeco-1.1.2-1.16.5.jar
creategears-1.16.5-1.3.3.jar
create-mc1.16.5_v0.3.2g.jar
createplus-1.16.4_v0.3.2.1.jar
create-stuff-additions1.16.5_v1.1.6.jar
CreateTweaker-1.0.0.28.jar
CreativeCore_v2.2.1_mc1.16.5.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.5-4.1.0.0.jar
CuriosQuarkOBP-1.16.5-1.0.2.jar
Curious+Armor+Stands-1.16.5-2.2.0.jar
curiouselytra-forge-1.16.5-4.0.2.4.jar
customgamerules-1.16.4-1.1.1.jar
cyclepaintings_1.16.5-2.7.jar
decorative_blocks-1.16.4-1.7.2.jar
dimensionalpocketsii-1.16.5-1.5.0-universal.jar
Disenchanting-forge-1.16.5-1.7.2.jar
dismountentity_1.16.5-1.5.jar
DoubleSlabs-1.16-3.7.3.jar
DynamicSurroundings-1.16.5-4.0.5.0.jar
elevatorid-1.16.5-1.7.13.jar
EnchantmentDescriptions-1.16.5-7.1.20.jar
EnderStorage-1.16.5-2.8.0.170-universal.jar
environmental-1.16.5-1.1.1.jar
Exchangers-1.16.5-3.0.2.jar
extlights-3.3.jar
ExtraButtons-1.16.3-4.0.1.jar
FastLeafDecay-v25.2.jar
findme-1.16.3-2.2.1.0.jar
floormats-1.16.5-v1.5.1.jar
flywheel-1.16-0.2.5.jar
FramedBlocks-2.16.3.jar
framedcompactdrawers-1.16-2.2.1.jar
geckolib-forge-1.16.5-3.0.106.jar
glassential-forge-1.16.5-1.1.7.jar
goldenhopper-1.2.1-1.16.3.jar
gravestone-1.16.5-1.0.7.jar
grindstonesharpertools_1.16.5-2.2.jar
GunpowderLib-1.16.5-1.2.2.jar
hexerei-0.1.4.jar
InsaneLib-1.4.2-mc1.16.5.jar
Inspirations-1.16.5-1.2.3.38.jar
InventoryEssentials_1.16.5-2.3.2.jar
InventoryHud_[1.16.2-1.16.5].forge-3.4.1.jar
InventoryProfilesNext-forge-1.16-1.5.0.jar
itemcollectors-1.1.7-forge-mc1.16.jar
ItemPhysic_v1.4.18_mc1.16.5.jar
jei-1.16.5-7.8.0.1009.jar
JEIEnchantmentInfo-1.16.5-1.3.0.jar
journeymap-1.16.5-5.8.5p6.jar
JustEnoughResources-1.16.5-0.12.1.133.jar
keywizard-forge-2.0.1.jar
Kiwi-1.16.5-3.6.1.jar
KleeSlabs_1.16.5-9.2.1.jar
kotlinforforge-1.16.0-obf.jar
lazierae2-1.16.5-2.0.5.jar
lightspeed-1.16.5-1.0.3.jar
magicfeather-1.16.2-3.2.0.jar
Mantle-1.16.5-1.6.157.jar
moreminecarts-1.3.17.jar
moremountedstorages-1.3.0.jar
MouseTweaks-2.14-mc1.16.2.jar
Neat+1.7-27.jar
NotEnoughEnergistics-1.16.5-0.1.jar
openbackup-1.16.x-1.1.1.jar
OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar
PassableFoliage-1.16.5-2.4.0.jar
Placebo-1.16.5-4.7.0.jar
playerplates-1.16.3-forge-1.0.0.jar
plonk-1.16.5-10.0.4.jar
ProgressiveBosses-3.4.3-mc1.16.5.jar
PuzzlesLib-v1.0.15-1.16.5-Forge.jar
QuarkOddities-1.16.3.jar
Quark-r2.4-322.jar
radon-0.8.0a.jar
rainbegoneritual_1.16.5-1.7.jar
rsgauges-1.16.5-1.2.16.jar
scaffoldingpower-1.16.5-1.3.0.jar
scarper-2.0.0.jar
selene-1.16.5-1.9.0.jar
shelf-1.2.jar
simplemagnets-1.1.9-forge-mc1.16.jar
SnowRealMagic-1.16.4-2.9.0.jar
SoL-Carrot-1.16.5-1.10.1.jar
steampowered-1.16.5-1.2.6.jar
step-1.16.4-1.1.0.jar
StorageDrawers-1.16.3-8.5.2.jar
StrongerSnowballs-1.16.5-5.0.1.jar
supermartijn642configlib-1.1.6-forge-mc1.16.jar
supermartijn642corelib-1.1.7-forge-mc1.16.jar
supplementaries-1.16.5-0.18.5.jar
theoneprobe-1.16-3.1.7.jar
ToolBelt-1.16.5-1.16.3.jar
torchoptimizer-1.16.5-2.4.8.jar
twilightforest-1.16.5-4.0.870-universal.jar
untitledduckmod-0.3.0-forge.jar
upgrade_aquatic-1.16.5-3.1.2.jar
Uppers-0.3.2.jar
veinmining-forge-1.16.5-0.18.jar
VTweaks-1.16.4-3.6.2.jar
Waystones_1.16.5-7.6.4.jar
weakerspiderwebs_1.16.5-2.7.jar
WorldEdit-CUI-FE3-1.16.5-3.0.9.jar
worldedit-mod-7.2.5-dist.jar
YungsApi-1.16.4-Forge-13.jar
YungsExtras-Forge-1.16.4-1.0.jar
abnormals_core-1.16.5-3.3.1.jar
actuallycompatible-0.1.2.jar
ae2wtlib-0.3.3-1.16.5.jar
AEAdditions-1.16.5-2.0.1.jar
AEInfinityBooster-1.16.5-1.0.0+12.jar
alloyed-1.16.5-v0.3a.jar
Apotheosis-1.16.5-4.8.9A0.jar
appleskin-forge-mc1.16.x-2.4.0.jar
appliedenergistics2-8.4.7.jar
AppliedEnergisticsTweaker-1.0.0.15.jar
architectury-1.32.67.jar
astikorcarts-1.16.5-1.1.1.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.2.jar
backpacked-2.1.12-1.16.5.jar
bambooeverything-1.16.5-1.0.1-forge.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterDungeons-1.16.4-1.2.1.jar
BetterF3-1.5.0-Forge-1.16.5.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar

**Comment by Mari023** [comment]
the 1.16.5 forge version wasn't made by me, and I can't provide support for it.

**Comment by Nexow91** [comment]
> the 1.16.5 forge version wasn't made by me, and I can't provide support for it.

Too bad I have now also again the configs recreate but the same problem. too bad that there is no way on your part to fix it yet thanks for the quick feedback. 

Greetings
