### ISSUE TITLE
Game fails to start

### ISSUE THREAD

**Issue by Frost993** [Mari023/AE2WirelessTerminalLibrary#206]
Game fails to start up.

Log: https://pastebin.com/10QFeyAq

Mods:
fabric-api-0.83.1+1.20.1.jar
cloth-config-11.0.99-fabric.jar
trinkets-3.7.0.jar
appliedenergistics2-fabric-15.0.0-alpha.jar
ae2wtlib-15.0.0-beta.jar

**Comment by Mari023** [comment]
should be fixed in 15.0.1-beta
