### ISSUE TITLE
Mixin apply failed (Crash on startup) (1.20.1-Forge)

### ISSUE THREAD

**Issue by Ve6om** [Mari023/AE2WirelessTerminalLibrary#210]
ae2wtlib-15.0.1-betag.jar

Log:
https://paste.gg/p/anonymous/fe9a1147055d49ed9611e3b12f763203

**Comment by Ve6om** [comment]
Turns out it's my own mod causing the crash. I don't touch anything relating to inventory / item stack mixins though?

**Comment by Mari023** [comment]
oh great, #163 is an issue on 1.20.1 too.

> Turns out it's my own mod causing the crash. I don't touch anything relating to inventory / item stack mixins though?

I am pretty sure it isn't your mod causing it, this bug seems quite random, and only happens with some mod combinations

I haven't been able to reproduce it myself (it doesn't help that the modlist is always something like atm and a bunch of other mods )
