### ISSUE TITLE
Failure to Initialize Game. 

### ISSUE THREAD

**Issue by GenzongGaming** [Mari023/AE2WirelessTerminalLibrary#211]
Not sure if it's Issue 163 but, here's the log and the crash report. 

MC Version 1.19.2 
Latest version of AE2WTLib
AE2 v12.9.5 
Forge v42.3.14

[crash-2023-07-17_22.50.50-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/12075420/crash-2023-07-17_22.50.50-client.txt)
[latest.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/12075422/latest.log)

**Comment by GenzongGaming** [comment]
I went through every mod and ultimately figured out that it was AE2WTLib that was causing it. Remove it and it boots and a world loads perfectly fine.

**Comment by Mari023** [comment]
it is indeed a variant of #163 

tho there are a few weird things with your log
1. after failing to apply the mixins, it just continues 
2. it then tries to apply this mixin for 2 more times (a total of 3 times)
3. and then it crashes on something unrelated

**Comment by GenzongGaming** [comment]
> 3. and then it crashes on something unrelated

Does it say what it crashed on by chance? Because without AE2WTLib everything works fine

**Comment by GenzongGaming** [comment]
Additionally, anything else I can possibly do to help diagnose this? Any Mods that help with Crash Reports such as this or a modlist or anything?

**Comment by GenzongGaming** [comment]
[mod-list_2023-07-18_16.08.57.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/12088662/mod-list_2023-07-18_16.08.57.txt)
Modlist if this helps any (Not Including AE2WTLib)

**Comment by Mari023** [comment]
> > 3. and then it crashes on something unrelated
> 
> Does it say what it crashed on by chance? Because without AE2WTLib everything works fine

> java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.client.renderer.RenderType

it fails to load a class which should be present, (which ae2wtlib doesn't touch)

tho it should have already crashed after failing to apply the mixin for the first time
by not crashing it likely left minecraft in a broken state.
(that is also why it works without ae2wtlib)

---


> Additionally, anything else I can possibly do to help diagnose this? Any Mods that help with Crash Reports such as this or anything?

no, not really.
I know where it happens, and how to work around that, but I have no clue why it happens or how to debug it

**Comment by GenzongGaming** [comment]
> I know where it happens, and how to work around that, but I have no clue why it happens or how to debug it

Ah :/ Well hell. I wish you luck and hope you can find the issue. It's pretty much broken for me since  and I'm dying without my AiO Wireless Terminals X, x from 1.18 - 1.20 :/

**Comment by Mari023** [comment]
can you try this test build and see if it still crashes?
[test.zip](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/12109208/test.zip)

> Additionally, are there any known incompatibilities with AE2WTLib

actually, now reading about this, someone said createindustry can trigger this bug (tho it works fine for me if I just install ae2wtlib and createindustry)
if the test build above fixes this issue, then I know what the exact problem is, and it would be both mods fault

> and other AE2 mods

optifine breaks some ae2 features, but optifine breaks like every second mod

**Comment by GenzongGaming** [comment]
> oops, that build is for the wrong minecraft version, here is the correct one: [test.zip](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/12109827/test.zip)

It works!! Game booted up just fine and I was able to load into the world and spawn myself all the terminal variants! :D

> actually, now reading about this, someone said createindustry can trigger this bug (tho it works fine for me if I just install ae2wtlib and createindustry)
> if the test build above fixes this issue, then I know what the exact problem is, and it would be both mods fault

I actually did  have Create Industry I believe. I have Create 5.1 and everything that's updated for 5.1 Not sure that was actually the issue or what but here's a new log so you can see all the interactions incase that helps. The only issue is that it seems the player inventory screen is a little borked. 
![image](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/69611622/4965bdc2-c261-42f8-8b4b-1b81a0f37a99)

https://paste.atlauncher.com/view/99160ea3-5b26-42ac-8f78-e838e89830d5

**Comment by Mari023** [comment]
> It works!!

Great!
I will make a proper release with the fix soon

about the texture issue, you do have a texturepack with dark mode GUIs?
can you give me a link to it?

at some point I changed the way the GUI works, and that seems to have broken it, but it should be an easy fix (assuming there isn't already a fixed version available)

**Comment by GenzongGaming** [comment]
> about the texture issue, you do have a texturepack with dark mode GUIs?
> can you give me a link to it?

Ah, yeah I do. Totally forgot about adding that to the pack I'm tryna make and PAXI'd it. Here's the link to it. https://www.curseforge.com/minecraft/texture-packs/default-dark-mode

**Comment by Mari023** [comment]
> > about the texture issue, you do have a texturepack with dark mode GUIs?
> > can you give me a link to it?
> 
> Ah, yeah I do. Totally forgot about adding that to the pack I'm tryna make and PAXI'd it. Here's the link to it. https://www.curseforge.com/minecraft/texture-packs/default-dark-mode

there is a fix, but only for later minecraft versions https://github.com/nebuIr/Default-Dark-Mode/issues/120
you can fix it yourself by replacing the file `assets/ae2/textures/wtlib/guis/extras.png` in the 1.29.2 version with the one from the  latest (1.20) version of that texturepack
 
> Hopefully with this update you can permanently close #163 X ,x PS, was Create 5.0+ and it's 5.0+ Addons the issue again?

the issue is that both me and createindustry have a refmap called `mixin.refmap.json` (you are supposed to put the modid in the filename), causing one to be overwritten, and missing some data
for the fixed version, I just renamed it

**Comment by GenzongGaming** [comment]
> there is a fix, but only for later minecraft versions [nebuIr/Default-Dark-Mode#120](https://github.com/nebuIr/Default-Dark-Mode/issues/120)
> you can fix it yourself by replacing the file `assets/ae2/textures/wtlib/guis/extras.png` in the 1.29.2 version with the one from the latest (1.20) version of that texturepack

That fixed it. Ty. 



> the issue is that both me and createindustry have a refmap called `mixin.refmap.json` (you are supposed to put the modid in the filename), causing one to be overwritten, and missing some data
> for the fixed version, I just renamed it

Ofc it was something so simple haha. Well, hopefully anyone that looks up similar issues like this in the future comes across this post and goes "huh.... let me check the obvious thing that's so obvious it couldn't possible be that" 

Regardless many thanks for the assistance. Happy to have AE2WTLib back >.  <

**Comment by Mari023** [comment]
the fix is public now
