### ISSUE TITLE
[1.20.1] server crash when opening terminal with broken link target

### ISSUE THREAD

**Issue by sreny1** [Mari023/AE2WirelessTerminalLibrary#213]
When you got a wireless terminal with a quantum bridge card (+ quantum ring etc.) and its linked to a wireless access point. 
you then break the access point. 
then you open the wireless terminal.
the game + server crashes

mod version: 15.0.6-beta

**Comment by Mari023** [comment]
can you please post the crash report?

**Comment by sreny1** [comment]
@Mari023 https://mclo.gs/fQOk0E7

**Comment by Mari023** [comment]
this seems like an issue with AEInfinityBooster, tho I am not 100% sure it wouldn't happen without it
can you please test if the crash happens without AEInfinityBooster?

It could also be a bad interaction between ae2wtlib and AEInfinityBooster

**Comment by Mari023** [comment]
looking a bit more at the ae2 code, my code and AEInfinityBooster's code, it is probably a bad interaction between the two addons

**Comment by Mari023** [comment]
looking more at the code, it might be fixable on my side

**Comment by sreny1** [comment]
There was no infinity booster involved, unless you mean without the mod installed at all.
And sadly removing a mod from a modpack isnt an option (/solution) when playing on a server unless its a client side mod only

Would be really nice if it is fixable on your side. Nullpointers should be easy to avoid in my experience.
Else i may forward this to the infinity booster repo

**Comment by Mari023** [comment]
Just having it installed should be enough to trigger this bug according to the source code

I am working on a fix for ae2wtlib, I just have to test it
