### ISSUE TITLE
1.18.2 Wireless Booster Not Working

### ISSUE THREAD

**Issue by DracoFlame90** [Mari023/AE2WirelessTerminalLibrary#218]
Playing on the modpack Dawncraft with a handful of other mods included that I like for 1.18.2, such as Ice and Fire, Mana and Artifice, Mekanism, Thermal Series and a few others. Added in the AE2 mods, and trying to get the Wireless Crafting Terminal to work. It'll work while I'm anywhere within my base, but if I go to far away it stops working and says "station could not be found" I'm not sure what the actual range is before it says this.

The infinity booster card is suppose to work at infinite range and across dimensions according to the mod page, but I'm getting this message constantly. If I take a waygate it might open once, then it says the station could not be found. I don't know if it is a conflict with another mod, or if its just not working as it should in 1.18.2.

I've also tried the mod AEInfinityBooster, which adds an Infinity/DImension Card, and that one doesn't seem to be working for me either. The Dawncraft modpack has stuff scattered thousands of blocks away, and I'm getting tired of having to haul backpacks with me to do a little bit of exploring and would like to be able to use the wireless terminal at any distance, but it just won't work.

**Comment by Mari023** [comment]
your system has to be chunkloaded, otherwise the infinity booster card won't work
