### ISSUE TITLE
Suggestion: Creative Energy Cell variants of wireless terminals.

### ISSUE THREAD

**Issue by PlayfulPiano** [Mari023/AE2WirelessTerminalLibrary#219]
For those who are using AE2 for its storage system without the interest of working with energy management, it would be nice if there were variants of the wireless terminals that had no energy requirement, needing a creative energy cell for its crafting recipe. Obviously this wouldn't be accessible to standard playthroughs, as creative energy cells are not available unless you give yourself one or create a custom crafting recipe for the item.

This theoretically should make it function identically to a remote storage access from terraria's magicstorage mod, which is based on AE2 but without the power generation.

(it would also be nice, albeit probably not of your interest, to have this addition backported for 1.18.2, as that's the version I"m using atm due to the mojang changes with chat reports).

**Comment by Mari023** [comment]
since 1.19.2+ the quantum bridge charges the terminal, and if you have a creative cell on the network, that will already basically work like this

however for 1.18.2, you are out of luck

but there are mods to remove chat reporting (for both client and server)
