### ISSUE TITLE
[Prominence II Fabric Modpack] [1.20.1] Wireless Terminal drops down to 50% when using QB Card and Singularity

### ISSUE THREAD

**Issue by K-Anudeep** [Mari023/AE2WirelessTerminalLibrary#220]
Hi, thanks for the support on this mod!

I want to ask and clarify some issues-
1) When I have the Singularity and QB Card, everything works fine, I can access the files at infinite distance and dimensions but the Wireless Crafting Terminal always falls down to 50%, even after charging to 100% if I open it, drops down to 50%.

2) Is the Wireless Crafting Terminal energy drain intended to be this fast at long distances and in another dimensions? I can only use it for seconds before it completely depletes. 

Is there a way to make the QNB give more power to the wireless terminal? Is it dependent on my powersource or is there a way I'm missing to increase infinite distance charge rate?

3) Do I have to make multiple Quantum Network Bridges for every player on the server for them to use QB upgrades or is there a way to make use of one QNB?

4) Minor visual bug, I see a line pop up whenever I open the wireless terminal saying "Linked Network cannot be found", even though I am linked and it's working. 

One final thing, I see in the mod description for Curseforge says theres infinity booster card but there is no such thing like that here, I guess it's old? Not sure about that. Just a heads up.

**Comment by Mari023** [comment]
1. the dropping to 50% is intended, that is the terminal reverse charging the network to make sure the network doesn't run out of energy
2. it is linked to the amount a terminal at maximum range is consuming, maybe I should change it to whatever a quantum bridge uses

the terminal charges as much as it can draw from the network without the network's energy storage dropping below 50%
if it doesn't charge fast enough, you need to add some energy storage to your network (and make sure your network gets enough energy)

3. you need one for every player
4. that is know, but I don't know how to fix it yet

**Comment by Mari023** [comment]
I opened separate tracking issues for 2 (#222) and 4 (#221)
