### ISSUE TITLE
Creative search function broken

### ISSUE THREAD

**Issue by castilio20** [Mari023/AE2WirelessTerminalLibrary#224]
It seems your mod + emi brakes the creative search function it deosnt happen evry time 
https://pastebin.com/zecd20bg

**Comment by Mari023** [comment]
turns out I did *not* fix it

also this might be an emi bug
https://discord.com/channels/922828438274986004/922828438274986007/1177286400694030426

**Comment by castilio20** [comment]
https://github.com/emilyploszaj/emi/issues/283

**Comment by castilio20** [comment]
![Screenshot_1](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/76228548/57d99aae-1d2d-4f4f-92ca-9492ad8542a6)

**Comment by Mari023** [comment]
should be fixed in the next release
