### ISSUE TITLE
Fabric version 12.9.5 duplication glitch

### ISSUE THREAD

**Issue by Matakor** [Mari023/AE2WirelessTerminalLibrary#228]
While I'm currently using this in the Statech pack, I believe it's exclusive to AEWTLib. I have found that by utilizing the AE2 wireless terminal and with the magnet card installed and set to insert to ME system I can cause a dupe with the minecraft cutting board.

>place anything on cutting board
>pick up from cutting board with empty hand
>item is duped when placed into ME system using magnet card in AE2 wireless terminal

I have noticed one or two odd items cause an immediate CTD, but does not corrupt the world and seems to even keep the duped item after crashing. Most items/blocks/etc instead just get duped.

**Comment by Mari023** [comment]
I'll have to test the dupe, can you please post a crash report of the an item that crashes?

**Comment by Mari023** [comment]
okay, I can reproduce the dupe, I'll have to see what I can do to fix this

**Comment by Matakor** [comment]
Can do.
[crash-2023-11-06_17.44.28-client.txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/13275420/crash-2023-11-06_17.44.28-client.txt)

**Comment by Matakor** [comment]
the item in question in the statech pack was an aluminum cable. I haven't tried others, just in case it starts crashing too much.

**Comment by Mari023** [comment]
I released a version wich patches the dupe, and it might also fix the crash

if it still crashes with the new version, please post a new crashlog here
