### ISSUE TITLE
Wireless Out of Range

### ISSUE THREAD

**Issue by HeadHunterShiv** [Mari023/AE2WirelessTerminalLibrary#231]
Hi, I've been playing All of Fabric 6 and i decided to add the mod to use the quantumn bridge card. I have the bridge set up and the singularity but still when i go a bit far it stops working. What should i do

**Comment by Mari023** [comment]
Is your network chunkloaded?
what does it say?

**Comment by HeadHunterShiv** [comment]
> Is your network chunkloaded? what does the terminal say when you try to open it?

Well i fixed it forceloading did the job for me
