### ISSUE TITLE
[1.20.1] NeoForge crash

### ISSUE THREAD

**Issue by michlbro** [Mari023/AE2WirelessTerminalLibrary#238]
Realised that ae2wtlib-15.2.1 was causing a crash upon "loading bootstrap resources". Removed all the mods apart from appliedenergistics2-forge-15.0.15 and it still crashed.
Forge Version: 1.20.1-47.1.84
Log: https://mclo.gs/Di4fgm4

**Comment by Mari023** [comment]
>Mod ID: 'ae2', Requested by: 'ae2wtlib', Expected range: '[15.0.12,16.0.0)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'ae2wtlib', Expected range: '\*', Actual version: '[MISSING]'
	Mod ID: 'architectury', Requested by: 'ae2wtlib', Expected range: '\*', Actual version: '[MISSING]'
	Mod ID: 'curios', Requested by: 'ae2wtlib', Expected range: ' \*', Actual version: '[MISSING]'
	
you need `cloth_config` `architectury` and `curios`
it also seems you *don't* have appliedenergistics2 installed

**Comment by michlbro** [comment]
Right, after installing Curios the mod works perfectly👍.

I don't know why AE2 is missing since it was in the mods folder.
