### ISSUE TITLE
Magnet and restock modes?

### ISSUE THREAD

**Issue by PrincessRTFM** [Mari023/AE2WirelessTerminalLibrary#239]
I see there are two filter sets, "pickup" and "insert", and there's a keybind for "restock" mode. Neither seems to be documented anywhere.

With some trial and error, I _think_ I figured out the filter sets for the magnet modes - how if you set the magnet to pickup to ME, then only things allowed by the insert filter will go to the system and everything else goes to your inventory. Weirdly, if I set both filters to whitelist mode and keep them empty, the magnet _still_ picks things up at a distance when enabled, which may be a bug.

What I _can't_ figure out is how to configure restock mode, beyond the keybind to toggle it on and off; nothing is actually refilling in my inventory, even when it's turned on. The magnet mode filters don't seem to relate to restock mode, since no matter what I set them to, nothing is restocked into my inventory.

[UPDATE] Restock mode started restocking a block that I was placing, including seeming to _craft_ more of it, but doesn't restock items I toss on the ground. Is there any way to control the items that restock or what _causes_ them to be restocked? What about whether the system crafts more or only uses from storage?

**Comment by Mari023** [comment]
> I see there are two filter sets, "pickup" and "insert", and there's a keybind for "restock" mode. Neither seems to be documented anywhere.

currently, there isn't any documentation on anything, this is on my TODO basically since ae2 started it's own guidebook (#189), but I haven't done anything about it (partially because I am really bad at writing text)

> Weirdly, if I set both filters to whitelist mode and keep them empty, the magnet still picks things up at a distance when enabled, which may be a bug.

that is indeed a bug, thank you for reporting it.

> What I can't figure out is how to configure restock mode, beyond the keybind to toggle it on and off; nothing is actually refilling in my inventory, even when it's turned on. The magnet mode filters don't seem to relate to restock mode, since no matter what I set them to, nothing is restocked into my inventory.


> [UPDATE] Restock mode started restocking a block that I was placing, including seeming to craft more of it, but doesn't restock items I toss on the ground. Is there any way to control the items that restock or what causes them to be restocked? What about whether the system crafts more or only uses from storage?


Restock is somewhat limited in what it can do, specifically the only things it can do are block placements, and using an item in the air (e.g. eating should work)
there is an issue for things that would be nice if they worked but don't. (#136)

there is no way to configure it beyond the toggle, tho imo this isn't really necessary

it shouldn't be crafting anything, tho I think it would be nice if it could do it, I added it to the tracking issue for restock (#136) (I think crafting *would* need more configuration)

**Comment by Mari023** [comment]
I fixed the bug with empty filters in dev, it will be released whenever I do the first 1.20.4+ release

**Comment by PrincessRTFM** [comment]
I won't see that since I'm playing ATM9 which is a 1.20.1 pack, but I'm glad it's fixed!

As for what restocking "handles", I think Create's toolboxes are a fantastic implementation and I'd love to see something similar here. They keep items to be restocked at a constant half-stack, and anything reducing the stack size below that causes it to be brought back up while anything increasing the amount (like picking something up) takes the excess off. It would need filtering to work reasonably, and I'm pretty sure it would have to be done by checking player inventory every tick, so I understand if you'd rather not add it - especially since it'd be a total overhaul. Just wanted to put the idea out there!

**Comment by Mari023** [comment]
closing this since the bug is fixed, restock now works for more cases, and the missing documentation is already tracked in another issue.
