### ISSUE TITLE
Crash with JEI when opening inventory

### ISSUE THREAD

**Issue by muggleorwizard** [Mari023/AE2WirelessTerminalLibrary#240]
The issie is: Item has no registry name: 1 ItemWUT[unregistered] de.mari_023.ae2wtlib.wut.ItemWUT nbt:{crafting:1b}
Crash report is below. It points to JEI, but specifically mentions ae2wtlib.wut.ItemWUT
Any ideas as to what the issue might be? Thanks!

[crash-2024-01-26_09.05.48-client(1).txt](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/14067202/crash-2024-01-26_09.05.48-client.1.txt)

**Comment by Mari023** [comment]
I can't reproduce this with just ae2wtlib, JEI and their dependencies, so this is caused by some other mod

**Comment by muggleorwizard** [comment]
I've noticed that I can only reproduce on a server environment, single player does not have issue

**Comment by Mari023** [comment]
I can't reproduce it on a server either

**Comment by advtech92** [comment]
I too had this issue. Here is the mods in my pack ([0.0.11](https://docs.google.com/spreadsheets/d/1o5eHwRZshhYG-ebu4K1UvBYsPeZ1ZcCg5j4U1sdsRRA/edit#gid=78368348))

**Comment by Mari023** [comment]
can you post the log? maybe that contains some information 

otherwise you could try a binary search to find out which mod is causing this, tho that is pretty annoying with that amount of mods
