### ISSUE TITLE
removes equippment

### ISSUE THREAD

**Issue by saphsara** [Mari023/AE2WirelessTerminalLibrary#246]
when you use only the wireless terminal when you type the letter r in the search menu all you equipment is removed and placed in the crafting table.  i was reading something about sorting mods , but not sure if that is an issue and can be fix we are using Inventory Profiles Next

**Comment by saphsara** [comment]
oh, running fabric 1.20.1 , mod pack saphsgamingworld fabric on curse

**Comment by Mari023** [comment]
this is an issue with whatever inventory sorting mod you are using.

good inventory sorting mods* can disable sorting per screen, and it shouldn't try to sort the wireless crafting terminal.
it might be possible for me to somehow tag the menu so it automatically knows it shouldn't sort it, I'll have to check that.

you can look if there is some kind of setting for you to disable sorting 

alternatively, as a workaround you can change the sort key to something you won't be typing in the terminal (e.g. one of the F1-12 keys)

---

*your pack uses Inventory Profiles Next, which I think does support this

**Comment by saphsara** [comment]
Thank you i will look more into the settings of that mod, i briefly looked and couldnt find anything. thank you for explaining. i will check config file.

**Comment by saphsara** [comment]
I have found the issue and i am having everyone manually fix it on thier end , because it is client side mod , inventory profile next in it setting has sorting hotkey set to r. i removed it and bam resolved, ty you for your help. i love your mod by the way. 

![sorting](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/33788318/652e411e-32b5-4028-a85c-5246e1dac2f5)

**Comment by saphsara** [comment]
it just stinks that is defaulted that way and everyone has to change it.  but thank you again for leading me in that right direction, even tho it wasnt your mod.

**Comment by Mari023** [comment]
Inventory Profiles Next has a way to fix this, they have a list of modded screens for which they need to handle sorting differently
I plan on making a PR for that soon, which should fix this for everyone

tho it is a bit weird that the keybind always triggers, regardless of focus

**Comment by Mari023** [comment]
I have opened a PR now that will stop reordering the armor (https://github.com/blackd/Inventory-Profiles/pull/396)
