### ISSUE TITLE
Unable to autocraft from wireless terminal over quantum bridge

### ISSUE THREAD

**Issue by Gaz492** [Mari023/AE2WirelessTerminalLibrary#252]
Im unable to autocraft anything through a wireless terminal thats connected over a quantum bridge, clicking next on the screen asking what quantities you want simply closes the UI so you are unable to start the crafting

**Comment by Mari023** [comment]
which minecraft version?

**Comment by Gaz492** [comment]
Sorry, its MC 1.20.4 and version 17.10.5-beta
