### ISSUE TITLE
currentTerminal isn't being used when opening universal terminal via keybind

### ISSUE THREAD

**Issue by mikerooni** [Mari023/AE2WirelessTerminalLibrary#253]
When opening a universal terminal via the `key_key.ae2.wireless_terminal` ("Open Wireless Terminal") keybind, it always opens the same terminal, with no way to influence which one that is.

In the case of using ExtendedAE's extended pattern provider terminal in a universal one, the extended pattern provider is opened each time. The item's `currentTerminal` nbt tag is not being used in this case.

The expected behavior here would be opening the most recently opened terminal (like it does when opening via right-clicking with the item), or alternatively being able to configure which one to open for the keybind.

**Comment by Mari023** [comment]
key_key.ae2.wireless_terminal is supposed to open either the normal wireless terminal, or the wireless crafting terminal, preferably the wireless crafting terminal in the universal terminal (regardless what the current terminal is)

it seems tho as the wireless extended pattern provider terminal is providing that keybind as the one to open the extended pattern provider terminal (it should use the same  keybind ae2wtlibs wireless pattern provider terminal uses)

I'll make a PR to ExtendedAE to fix this

**Comment by mikerooni** [comment]
Awesome, thank you!
