### ISSUE TITLE
Wireless terminals instatly draw 50% of their power when item is placed / taken out of ME system

### ISSUE THREAD

**Issue by josipglavas** [Mari023/AE2WirelessTerminalLibrary#256]
The issue is described in the title. When players are using quantum bridge card and singularity in a wireless terminal and when item is taken out or added into ME system it instantly draws 50% of its power. After that, the power consumption goes back to normal. 

The issue persists even if the item is charged constantly in inventory. It goes to 50% - gets charged to 100% and then goes back to 50% which causes a lot of issues.

**Comment by Mari023** [comment]
add one (or more) (dense) energy cells to your network, or update ae2wtlib
