### ISSUE TITLE
Better "Open next Terminal" Button

### ISSUE THREAD

**Issue by RuiXuqi** [Mari023/AE2WirelessTerminalLibrary#265]
![Screenshot_2024-05-12-20-37-50-255_com tungsten fcl](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/90179819/b58b13e0-2c55-4c43-a280-a26fadc17e11)
It is good to show which terminal will be opened on both the button and tooltip.
Also, it is a good idea to let you choose a therminal when you press shift and left chick on it.

**Comment by Mari023** [comment]
shift + click to select is already planned, see #94
