### ISSUE TITLE
Remove the energy bar on the icon of the tab

### ISSUE THREAD

**Issue by RuiXuqi** [Mari023/AE2WirelessTerminalLibrary#267]
![IMG_20240512_205638](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/90179819/892be09f-8dd4-4102-8073-ba152339d20e)
To show the mod more powerful

**Comment by Mari023** [comment]
22df46d2c54ff92e94bce264c6d73f381babb092 (1.20.4+) fixed this, it now shows the correct amount of energy in the icon

**Comment by Mari023** [comment]
oh, I thought you meant the crafting status icon, not the creative tab.
