### ISSUE TITLE
[Bug] Wireless Pattern Encoding Terminal does not work with JEI on Processing

### ISSUE THREAD

**Issue by heisluft** [Mari023/AE2WirelessTerminalLibrary#270]
The JEI + button does not work for the wireless Pattern Encoding Terminal on Processing Recipes, see attached screenshot
![image](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/30872344/7a3de51e-f050-493d-b320-840a9182e26b)

**Comment by Mari023** [comment]
that looks very much like EMI, and not like JEI.
if you are on 1.20.1, installing JEI in addition to EMI should fix this issue

**Comment by Mari023** [comment]
can you make a debug crashlog (hold F3 + c) and upload it on [github gist](https://gist.github.com/)?
