### ISSUE TITLE
neoforge 1.20.6 doesn't load mod correctly java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/player/EntityItemPickupEvent

### ISSUE THREAD

**Issue by BigFriendlyGamer88** [Mari023/AE2WirelessTerminalLibrary#276]
hello,

I am having an issue with the mod not loading in neoforge for 1.20.6, it tells me that it couldn't find the .class file inside the .jar file during loading. I have included both logs for convenience. 
[crash-2024-06-02_13.44.43-fml.txt](https://github.com/user-attachments/files/15524110/crash-2024-06-02_13.44.43-fml.txt)
[latest.log](https://github.com/user-attachments/files/15524111/latest.log)

if I have done something wrong please let me know.
thank you

**Comment by Mari023** [comment]
ah, right
I'll have to release a new version that works with the latest neoforge version.
I think I have this fixed in dev, but I'll have to test it first

**Comment by Mari023** [comment]
18.1.3-beta should fix this

**Comment by BigFriendlyGamer88** [comment]
awesome, thank you.
