### ISSUE TITLE
Wireless Universal Terminal (Pattern Encoding) doesn't work with JEI for creating patterns

### ISSUE THREAD

**Issue by mora-unie-youer** [Mari023/AE2WirelessTerminalLibrary#278]
I'm playing SkyGreg modpack, with latest AE2WTLib installed, as I can see.

I created universal wireless terminal:
![image](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/96782282/3f161eb9-be71-42dc-8c68-081dbdbd02bc)

And I want to encode patterns for GregTech recipes. When I try to add them in pattern encoding, it writes following:
![image](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/96782282/22b5c934-302d-499a-8902-b59f9865e801)

**Comment by mora-unie-youer** [comment]
Oh, as I can see it was fixed on the GregTech Modern side... Unfortunately I can't update to that version...

**Comment by Mari023** [comment]
duplicate of #273
