### ISSUE TITLE
I cant get the quantrum bridge to work.

### ISSUE THREAD

**Issue by Strandfeltdk** [Mari023/AE2WirelessTerminalLibrary#282]
I cant get the quantum bridge to work.
I have followed these steps by [shank3001](https://github.com/shank3001). 

"Create Singularity using Matter Condenser.
Create Quantum Entangled Singularity Pair (exploding TNT with Singularity and Ender Pearl or Ender Dust). This creates an entangled pair.
Craft Quantum Bridge Card.
Craft 8 Quantum Rings and 1 Quantum Link Chamber.
Build Quantum Bridge (Surround Quantum Link Chamber by the 8 Quantum Rings).
Link Quantum Bridge to AE network via cable (can only link to top, bottom, or sides, not on the corners of Quantum Ring).
Craft Wireless Access Point and attach to Quantum Bridge (again, can only attach to top, bottom, or sides, not on the corners of Quantum Ring).
Craft Security Terminal and attach to Quantum Ring.
Craft Wireless Crafting Terminal (one of many options). Can combine all wireless terminals in a crafting grid to create a multi-use wireless terminal.
Insert one of the Quantum Entangled Singularity Pairs in the Link Chamber.
Insert other Quantum Entangled Singularity in the Wireless Crafting Terminal along with the Quantum Bridge Card. They are slot specific and on the right hand side.
Insert Wireless Crafting Terminal into the right-hand slot of the Security Terminal to link it to the Quantum Bridge.
You now have infinite cross-dimensional wireless AE access."

I cant access network if im more than like 200-300 block away from the network.
i have taked a lot of screenshots. i think its my own mistake, but i have tried a lot of stuff, and also look on youtube.

Thank you in advance :-)

![2024-06-23_18 10 00](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/173623225/5c985f88-1f7a-4aaa-8751-3db0d71072da)
![2024-06-23_18 10 07](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/173623225/3226a15b-9df7-41d7-920c-e04b4c0a38cb)
![2024-06-23_18 10 18](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/173623225/20f06f8f-7447-44c5-ac14-d19ed848196a)
![2024-06-23_18 08 41](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/173623225/2e416b45-4773-4079-a4d0-9029b87b7a52)
![2024-06-23_18 08 45](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/173623225/4f438150-b462-4884-a3aa-163ae7185a9f)

**Comment by Mari023** [comment]
thank you for the detailed description of what you have done.

you did everything correctly.
the reason it doesn't work when you are not near network is because the chunks aren't loaded.
if you force load your network with a chunkloader (e.g. ae2s spatial anchor), it should work regardless where you are

**Comment by Strandfeltdk** [comment]
omg.. why didnt i think of this ...
Thank you for quick response !
