### ISSUE TITLE
[1.21] Terminals don't go into curio slots.

### ISSUE THREAD

**Issue by WhitePhant0m** [Mari023/AE2WirelessTerminalLibrary#285]
Tag seems to be wrong.

**Comment by Mari023** [comment]
There are like half a million curio forks for 1.21 right now, if those forks are not implementing the curio spec correctly, that is on them.

I believe there is some work to get a unified curio api into neoforge, if that gets released I'll look into fixing the curio related bugs.

**Comment by WhitePhant0m** [comment]
i meant as in, you have it as `curios/tags/items` while it should be `curios/tags/item`
and from what i quickly saw in the code, you use AE2s curio compat for yours, right?
![image](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/33400200/467c3b03-3df9-4c1f-9c6f-209781b22030)
![image](https://github.com/Mari023/AE2WirelessTerminalLibrary/assets/33400200/22478c41-c8da-469a-990f-4b9e8eec0f6b)
AE2s curio compat works fine.

**Comment by Mari023** [comment]
ah right, minecraft renamed the folders, I'll have to fix that
