### ISSUE TITLE
(1.19.2) Cannot add cards/singularity to a wireless terminal when out of range

### ISSUE THREAD

**Issue by Tholp1** [Mari023/AE2WirelessTerminalLibrary#289]
UI instantly closes before anything can be done.
Mostly an issue when trying to add a quantum bridge card while away from your system or when you have a system on something like a Valkyrien Skies object where its technically past the world border

**Comment by Mari023** [comment]
1.19.2 is no longer supported, and won't receive any more updates.

This is fixed in newer versions, where the terminal now just always opens and stays open.
