### ISSUE TITLE
Issue with connecting new terminal.

### ISSUE THREAD

**Issue by Strandfeltdk** [Mari023/AE2WirelessTerminalLibrary#291]
So.. i have lost my wireless terminal at some point..
but the issue is the when is try to set up the quantum link chamber, with a new singularity i dosnt work.
i have destoried the one that was in the champer, and replaced it.

I have build a whole new set og rings and champer and linked to a new wireless access point.
an ancher is connected.

The Power supply is connected to the side of a quantum ring. 

Wireless terminal is fully charged

I have tried to search to see if you can like untangle the quantum network, but didnt find anything.

Thank you in advance :-)

I have but in a screenshot of the setup. (which is identical to the one before i lost the terminal).

![2024-07-14_16 29 46](https://github.com/user-attachments/assets/25827a38-5be3-4fa2-858f-f9e8358fe7a7)

**Comment by Mari023** [comment]
did you put in a quantum bridge card in your new terminal?
it might also worth checking if you used the correct singularity, if they stack they are the same an should connect

**Comment by Strandfeltdk** [comment]
I made a new singualarty with enderdust and tiny tnt. 
And it is in the quantum slot :)

**Comment by Mari023** [comment]
but did you make a new quantum bridge card too?

**Comment by Strandfeltdk** [comment]
well.. i didnt have any inserted haha.
woops by bad :-)
