### ISSUE TITLE
extendedAE incompatibility.

### ISSUE THREAD

**Issue by MrChuw** [Mari023/AE2WirelessTerminalLibrary#292]
Crash when trying to open the game with extendedAE.

NeoForge version: 21.0.95
AE2WTLib version: 19.0.10-beta (I tried with all available versions.)
ExtendedAE version: 1.21-1.1.0-neoforge (I tried with all available versions.)

[crash-2024-07-15_22.51.53-fml.txt](https://github.com/user-attachments/files/16242177/crash-2024-07-15_22.51.53-fml.txt)

**Comment by Mari023** [comment]
fixed in ExtendedAE (https://github.com/GlodBlock/ExtendedAE/issues/209)
