### ISSUE TITLE
"Linked network cannot be found" message is there all the time. Everything works fine.

### ISSUE THREAD

**Issue by ashzure-github** [Mari023/AE2WirelessTerminalLibrary#293]
I've troubleshooted every variable in my system and restarted my system + the game. I found a closed issue back in december 2023 about this but I'm getting it now so I'm opening a new one for visibility.

This is on 1.20.1 in the atm9 modpack. I asked for help on the discord for the pack but theyre stumped so im assuming an ae2 wireless bug.

**Comment by Mari023** [comment]
(this is a slightly different issue than #221, since it affects version after 15.2.1 where #221 was fixed)

1.20.1 is not supported anymore, and won't receive further updates.
1.21+ uses a different system for notifying the user if the terminal doesn't work, so it doesn't have this issue anymore
