### ISSUE TITLE
AE2 Item recipes not appearing with REI

### ISSUE THREAD

**Issue by Aurytis11** [Mari023/AE2WirelessTerminalLibrary#301]
Minecraft Version: 1.21 Neoforge
Mod Version: 19.1.3

Originally i posted a comment under an [issue on the ae2 github](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8116)  and narrowed down that it's this mod that's causing the issue.

Original bug description (from the issue that i linked):
After pressing "R" on any item from AE2 it does not show recipe for anything in the mod.

**Comment by Mari023** [comment]
it seems like this no longer happens in newer REI versions on 1.21.1
if this happens again, please reopen the issue
