### ISSUE TITLE
[1.21.1-Neo] Mod causing intense fps drops when being in inventory while JEI is active. 

### ISSUE THREAD

**Issue by Gbergz** [Mari023/AE2WirelessTerminalLibrary#305]
When inventory is open with JEI on the side the FPS goes from my normal ~450 fps down to 70 fps.

Ran a spark client profiler and it seems to be caused by this mod? Not 100, but removing the mod does restore the FPS to the normal fps I'd expect.

![ss](https://github.com/user-attachments/assets/9510f983-3a49-4339-8cff-66ec92cf62a4)

![ss2](https://github.com/user-attachments/assets/d2d5830e-d05b-4187-b709-52fccbeaf4f4)

Profiler Link: https://spark.lucko.me/DkJi8Z3XuS

**Versions**
MC: 1.21.1
AE2: 19.0.22-beta
AE2 WT: 19.1.3
JEI: 19.18.0.199
NeoForge: 21.1.50

**Comment by Mari023** [comment]
just from a brief look, it seems like [https://github.com/Hidoni/Transmog](Transmog) might cause this, or at least make it worse
tho there are also a few thing I can do in ae2wtlib to make it less bad

**Comment by Mari023** [comment]
it looks like I repeatedly check if the player has a terminal while it doesn't have one
this greatly amplifies the weird interaction with transmog

transmog seems to do quite some expensive stuff in Player#getInventory() when it thinks it is rendering, and apparently ae2wtlib (potentially) changing the item amount counts as rendering for transmog

**Comment by Gbergz** [comment]
> tho there are also a few thing I can do in ae2wtlib to make it less bad

Any eta on this?

**Comment by Mari023** [comment]
> > tho there are also a few thing I can do in ae2wtlib to make it less bad
> 
> Any eta on this?

I don't make etas, but in this case I can say it won't happen soon, since I have exams I should learn for.

**Comment by Mari023** [comment]
19.1.4-beta (to be released soon) contains a workaround for this, tho I'll keep this issue open until I make the proper fix

**Comment by VaporeonScripts** [comment]
can u port that version for 1.21.1 too pls? cuz rn its only for 1.21

**Comment by Mari023** [comment]
> can u port that version for 1.21.1 too pls? cuz rn its only for 1.21

ah, right, I still haven't configured it to properly make 1.21.1 releases
I have marked the version as 1.21.1 on modrinth and cf now.

**Comment by Gbergz** [comment]
Can confirm newest update pretty much fixes this, thanks a lot! Appreciated.

**Comment by Mari023** [comment]
I have now replaced the workaround with a proper fix, in theory the performance should be slightly better than with the workaround but the difference is likely not noticable
