### ISSUE TITLE
MMB Doesn't work in Wireless Pattern Encoding Terminal

### ISSUE THREAD

**Issue by Grenzoocoon** [Mari023/AE2WirelessTerminalLibrary#306]
Playing ATM9 to the sky latest version of the pack, MMB doesn't bring up anything. For the crafting terminal it works fine to request more of an item if you have some, but it's an issue for processing patterns. I can't assign custom values like, 10 buckets of water to 10 hydrogen. Importing from a JEI recipe works fine, and removing stuff works as well. Same for the standalone terminal, and if it's part of universal one.

**Comment by Mari023** [comment]
whatever middle click sorting mod ATM9 is using is probably messing this up
you will probably have to rebind it from middle mouse or blacklist the screens
