### ISSUE TITLE
Sophisticated Backpack Auto Feed And Wireless Terminal Restock Issue

### ISSUE THREAD

**Issue by Vitier1** [Mari023/AE2WirelessTerminalLibrary#309]
I'm running into an issue where when I have the auto feed feature on in my backpack and the restock feature on in my wireless terminal, it's causing my food to be duplicated in both my backpack and ME system. When I took all but one stack of my steak out of my backpack and all of the steak out of my ME system it duplicated in both still, but the ME system duplicated based on the maximum steak that had previously been in it. At this point it's filling up a 64k drive every time. If there is a work around that would be great.

**Comment by Mari023** [comment]
(for reference: the related issue in Sophisticated Backpack https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1176)

I haven't looked into it yet tho
