### ISSUE TITLE
The crafting patterns written with the Wireless Pattern Encoding Terminal and those written with the ME Pattern Encoding Terminal are different.

### ISSUE THREAD

**Issue by TASC2** [Mari023/AE2WirelessTerminalLibrary#316]
The Wireless Pattern Encoding Terminal does not recognize 'fluid_bucket' as the 'fluid' itself. This causes an issue where the 'fluid' in the 'Terminal' cannot be called during automatic crafting. However, the ME Pattern Encoding Terminal does not have this problem. As shown in the images, Figure 1 shows the crafting patterns written with the ME Pattern Encoding Terminal, and Figure 2 shows the crafting patterns written with the Wireless Pattern Encoding Terminal
![1](https://github.com/user-attachments/assets/36c6a424-35d4-4067-8714-a104f4386fc1)
![2](https://github.com/user-attachments/assets/475fc63e-5555-4b90-a286-85e9db9a70a8)

**Comment by Mari023** [comment]
You have to enable fluid substitution for that to happen.
It is the rightmost of the little three buttons next to the crafting field, with a crossed out bucket.
If you enable that, the wireless pattern encoding terminal should also use the fluid in the pattern.

**Comment by TASC2** [comment]
thank you
