### ISSUE TITLE
Crash without Curios

### ISSUE THREAD

**Issue by SkeletonCold** [Mari023/AE2WirelessTerminalLibrary#4]
Crash Report:
https://paste.ubuntu.com/p/674ZDkRBD5/
Install mods:
![$ TUP}K3_7H5~WTGO%EBPCW](https://user-images.githubusercontent.com/72563159/112864831-ca8e4300-90ea-11eb-9884-9340f27c82bc.png)

**Comment by Mari023** [comment]
can you try it again with [Curios](https://www.curseforge.com/minecraft/mc-mods/curios-fabric)?
It shouldn't hard depend but I think it currently does

**Comment by SkeletonCold** [comment]
Thanks!Game is running, so will you add Curios to "Required Dependency"?

**Comment by Mari023** [comment]
I might do this as a workaround, but I would rather want it to not crash when curios is not present

**Comment by Mari023** [comment]
it should now not crash without curios
