### ISSUE TITLE
can not start crafting proccesses in wireless crafting terminal

### ISSUE THREAD

**Issue by MSandro** [Mari023/AE2WirelessTerminalLibrary#48]
I can not start crafting processes in a wireless crafting terminal. The Crafting Monitor button in the upper right doesn't work too.

AE2 8.2.0 Alpha 3
AE2WTLib 1.0.8 release

**Comment by Mari023** [comment]
seems like I messed up sub GUIs AGAIN...
I'll have a look at this

**Comment by Mari023** [comment]
apparently I fixed this in my trinkets branch, but not in master
It is fixed now, I will upload a working version later
