### ISSUE TITLE
I like Intellij IDEA

### ISSUE THREAD

**Issue by Domaman202** [Mari023/AE2WirelessTerminalLibrary#58]
![image](https://user-images.githubusercontent.com/51743763/119215001-fb8c6200-baf4-11eb-8f59-f7ddee91633b.png)

**Comment by Mari023** [comment]
I had a similar issue a few days ago, but I don't know how I got it resolved anymore
I think I tried Invalidating the caches but I am not sure if this was the solution
maybe rebuilding could help too
