### ISSUE TITLE
Translate Problems

### ISSUE THREAD

**Issue by Domaman202** [Mari023/AE2WirelessTerminalLibrary#60]
what does "Restock" do?

**Comment by Mari023** [comment]
It will take items out of the me system when you use them
e.g. you have half a stack of cobblestone in your hotbar, lots of cobblestone in your me, you are in range / have a infinity booster
you place a cobblestone, it will use up one, so you now have 31.
if restock is enabled, it will pull 33 cobblestone out of the me and put it in the slot.

**Comment by Domaman202** [comment]
ок, спасибо
ok, thx
