### ISSUE TITLE
terminal can be moved while in use (crashing sometimes)

### ISSUE THREAD

**Issue by irunatbullets** [Mari023/AE2WirelessTerminalLibrary#64]
A user on the server said "right, when you open it and then try to take it while its open it crashed the server last time I think". I'm not sure if this is very helpful or an accurate way to reproduce.

https://paste.alloffabric.com/iqafonipuk.yaml

**Comment by Mari023** [comment]
taking the terminal while it's open is pretty likely to fail somewhere
it is supposed to be locked like ae2 wireless terminal or the portable disk but for some reason the locking mechanism doesn't work.

**Comment by Mari023** [comment]
It was a *two line* fix :D
