### ISSUE TITLE
comability

### ISSUE THREAD

**Issue by szumaster** [Mari023/AE2WirelessTerminalLibrary#84]
with appliedenergistics2-fabric-8.4.0-alpha.3.jar

**Comment by szumaster** [comment]
yes, its work, but you know... cf need only approved releases

**Comment by Mari023** [comment]
I will publish an update soon, for now you can just use the build from [GitHub Actions](https://github.com/Mari023/AE2WirelessTerminalLibrary/suites/4018480037/artifacts/101531545)

**Comment by Mari023** [comment]
I published a new release, it should be available soon
