### ISSUE TITLE
Too much power consumption

### ISSUE THREAD

**Issue by Micalobia** [Mari023/AE2WirelessTerminalLibrary#95]
The wireless terminals go through their power supply quickly (at least with the infinity card it does, not sure if it changes power consumption), which makes it difficult to use a lot while out and about. I think either increasing power capacity or decreasing power consumption (or both) would help balance it a bit

**Comment by Mari023** [comment]
Increasing power capacity would be the better option

unless I made a mistake in the implementation, power consumption with an infinity booster card when out of range of an access point should be twice as high as it would be on the very edge of an access point (with maximum boosters)
decreasing consumption would only be possible to this limit (and I want no access point to be more expensive than the edge of it)

**Comment by Mari023** [comment]
the power capacity should be tied to the ae2 wireless terminal (increasing it's capacity should also increase the capacity of my terminals)

you can also set the outOfRangePowerMultiplier in the config (If I recall correctly 1.0 should be minimum, 2.0 is default)
this should decrease power consumption with an infinity booster card

**Comment by Mari023** [comment]
As of 1.18 the battery size of the Wireless Universal Terminal can now be increased independently from other terminals (and the default is now higher too)

**Comment by MysticalEnnio** [comment]
Im having the same issue. It uses 1% of 1m rf per second when out of bound. When changing the number outOfRangePowerMultiplier to 1.0 it is normal again(0.001% per second). With the value set to 2.0 It is at least 100 times higher.

**Comment by MysticalEnnio** [comment]
Even with a number like 1.1 the power usage is the same.

**Comment by Mari023** [comment]
version before 1.21 are not supported anymore. power usage got changed in newer versions and is now way lower.
