### ISSUE TITLE
AE2WTLib-1.2.5 incompatibilty with release version of AE2 8.4.0

### ISSUE THREAD

**Issue by DigiDuncan** [Mari023/AE2WirelessTerminalLibrary#98]
The latest 1.16 compatible release, 1.2.5, is incompatible with 8.4.0, even though it is compatible with 8.4.0-alpha3, seemingly being limited only by a far-too-strict version check.

**Comment by Mari023** [comment]
looking at ae2's curseforge page, there is no version 8.4.0 for fabric, only 8.4.0-alpha3, which is the latest (and last fabric 1.16 version of ae2).
